#!/bin/bash

set -e

# Actions made relative to this file's path
cd "$(dirname "${BASH_SOURCE[0]}")"

# Load utils
source ../utils

verbose_script

install_c_tools() {
  brew install clang-format
}

install_mongodb_community() {
  brew tap mongodb/brew
  brew install mongodb-community
}

install_python() {
  brew install python
}

main() {
  install_c_tools
  install_mongodb_community
  install_python
}

main
