#!/bin/bash

set -e

# Actions made relative to this file's path
cd "$(dirname "${BASH_SOURCE[0]}")"

# Load utils
source ../utils

verbose_script

main() {
  # Command Line Tools installed git is used by default.
  # Uncomment to use brew installed git.
  # brew install git
  return
}

main
