#!/bin/bash

set -e

# Actions made relative to this file's path
cd "$(dirname "${BASH_SOURCE[0]}")"

# Load utils
source ../utils

verbose_script

is_installed() {
  which brew &> /dev/null
}

install() {
  if ! is_installed
  then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  else
    homebrew_version=$(brew --version | head -1 | awk '{print $2}')
    echo "homebrew $homebrew_version is already installed."
  fi
}

update() {
  echo ''
  echo 'updating homebrew...'
  brew update
  brew upgrade
  brew cleanup
}

configure() {
  echo ''
  echo 'configuring homebrew...'
  brew analytics off
}

main() {
  install
  update
  configure
}

main
