#!/bin/bash

set -e

# Actions made relative to this file's path
cd "$(dirname "${BASH_SOURCE[0]}")"

# OS
./softwareupdate
./xcode

# Homebrew + packages
./homebrew
./zsh
./tmux
./vim
./git
./development
./deployment
./productivity
./apps
./fonts
