#!/bin/bash

set -e

# Actions made relative to this file's path
cd "$(dirname "${BASH_SOURCE[0]}")"

# OS
./softwareupdate
./xcode

# Homebrew + packages
./homebrew
./zsh
./tmux
# ./vim # netrw :Explore issue (last tested May 04, 2023)
./git
./development
./productivity
./apps
./fonts
