#!/bin/bash

set -e

# Actions made relative to this file's path
cd "$(dirname "${BASH_SOURCE[0]}")"

# Load utils
source ../utils

verbose_script

main() {
  brew install cloc
  brew install pandoc
  brew install pass
  brew install rsync
  brew install tree
}

main
