#!/bin/bash

# Basic git commit automation

set -e

repository="$1"

cd_to_repo() {
  cd "$repository"
}

autocommit_if_branch_is_dirty() {
  if [[ ! $(command git status --porcelain) == '' ]]
  then
    git add --all
    git commit --message="autocommit $(date +'%s')"
  fi
}

push_if_remote_exists() {
  if [[ $(command git remote) ]]
  then
    git push
  fi
}

main() {
  cd_to_repo
  autocommit_if_branch_is_dirty
  push_if_remote_exists
}

main
