#!/bin/sh

# Update all global packages installed via package management systems

set -e

update_homebrew() {
  echo '› brew update'
  brew update
  echo '› brew upgrade'
  brew upgrade
}

update_npm() {
  echo '› npm update -g'
  npm update -g
}

update_all() {
  update_homebrew
  update_npm
}

list_packages() {
  echo 'Homebrew'
  brew ls
  echo ''
  echo 'NPM'
  npm list -g --depth=0
}

while test $# -gt 0
do
  case "$1" in
    '-u'|'--update')
      update_all
      exit
      ;;
    'ls'|'list')
      list_packages
      exit
      ;;
    *)
      echo "Invalid option: $1"
      exit
      ;;
  esac
  shift
done
