#!/bin/sh

# Update all global packages installed via package management systems

set -e

update_homebrew() {
  echo '› brew update'
  brew update
  echo '› brew upgrade'
  brew upgrade
}

update_npm() {
  echo '› npm update -g'
  npm update -g
}

update_all() {
  update_homebrew
  update_npm
}

update_all
