[font]
size = 13
offset = { x = 0, y = 6 }

[colors]

[colors.primary]
foreground = "#d8d8d3"
background = "#1c1c1c"

[colors.normal]
black = "#000000"
red = "#f53116"
green = "#60cf09"
yellow = "#e6bf0a"
blue = "#5fb4f8"
magenta = "#f74b98"
cyan = "#0ad1f5"
white = "#e8e8e8"

[colors.bright]
black = "#606060"
red = "#f75c47"
green = "#78f516"
yellow = "#f6d22d"
blue = "#90cbfa"
magenta = "#f97cb4"
cyan = "#3bdaf7"
white = "#ffffff"

[cursor]
style = { shape = "Block", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
blink_interval = 500
blink_timeout = 0

[mouse]
hide_when_typing = true
