#!/bin/bash

set -e

# Actions made relative to this file's path
cd "$(dirname "${BASH_SOURCE[0]}")"

# Load utils
source ../utils.sh

verbose_script

is_xcode_command_line_tools_installed() {
  xcode-select --print-path &> /dev/null
}

install_xcode_command_line_tools() {
  if ! is_xcode_command_line_tools_installed
  then
    xcode-select --install
  else
    xcode_version=$(xcode-select -version | awk '{print ($3+0)}')
    echo "xcode-select $xcode_version is already installed."
  fi
}

main() {
  install_xcode_command_line_tools
}

main
